Fix ghost deployment

diff --git a/apps/ghost/deployment.yaml b/apps/ghost/deployment.yaml
--- a/apps/ghost/deployment.yaml
+++ b/apps/ghost/deployment.yaml
@@ -10,7 +10,7 @@ metadata:
     app.kubernetes.io/version: "5.8"
     app.kubernetes.io/component: ghost
     app.kubernetes.io/part-of: ghost
-    
+
 spec:
   replicas: 1
   selector:
@@ -24,130 +24,135 @@ spec:
     spec:
       automountServiceAccountToken: false # Disable automounting of service account token
       volumes:
-      - name: ghost-content
-        persistentVolumeClaim:
-          claimName: ghost-content-pvc
+        - name: ghost-content
+          persistentVolumeClaim:
+            claimName: ghost-content-pvc
 
-      - name: ghost-config-prod
-        secret:
-          secretName: ghost-config-prod
-          defaultMode: 420
+        - name: ghost-config-prod
+          secret:
+            secretName: ghost-config-prod
+            defaultMode: 420
 
-      - name: tmp
-        emptyDir:
-          sizeLimit: 64Mi
+        - name: tmp
+          emptyDir:
+            sizeLimit: 64Mi
 
       initContainers:
-      - name: ghost-init
-        image: docker.io/busybox:stable-musl
-        env:
-        - name: GHOST_INSTALL
-          value: /var/lib/ghost
-        - name: GHOST_CONTENT
-          value: /var/lib/ghost/content
-        - name: NODE_ENV
-          value: production
-        securityContext:
-          readOnlyRootFilesystem: true
-          allowPrivilegeEscalation: false
-        resources:
-          limits:
-            cpu: 900m
-            memory: 1000Mi
-          requests:
-            cpu: 100m
-            memory: 128Mi
-        command:
-          - /bin/sh
-          - '-c'
-          - |
-            set -e
+        - name: permission-fix
+          image: docker.io/busybox:stable-musl
+          env:
+            - name: GHOST_INSTALL
+              value: /home/nonroot/app/ghost
+            - name: GHOST_CONTENT
+              value: /home/nonroot/app/ghost/content
+            - name: NODE_ENV
+              value: production
+          securityContext:
+            readOnlyRootFilesystem: true
+            allowPrivilegeEscalation: false
+          resources:
+            limits:
+              cpu: 900m
+              memory: 1000Mi
+            requests:
+              cpu: 100m
+              memory: 128Mi
+          command:
+            - /bin/sh
+            - "-c"
+            - |
+              set -e
 
-            # Check if the following directories exists under $GHOST_CONTENT directory, if not, create them and then change the ownership to 1000:1000
-            export DIRS="files logs apps themes data public settings images media"
-            for dir in $DIRS; do
-              if [ ! -d $GHOST_CONTENT/$dir ]; then
-                echo "Creating $GHOST_CONTENT/$dir directory"
-                mkdir -pv $GHOST_CONTENT/$dir && chown -Rf 1000:1000 $GHOST_CONTENT/$dir || echo "Error creating $GHOST_CONTENT/$dir directory" && true
-              fi
-            done
+              export DIRS='files logs apps themes data public settings images media'
+              echo 'Check if base dirs exists, if not, create them'
+              echo "Directories to check: $DIRS"
+              for dir in $DIRS; do
+                if [ ! -d $GHOST_CONTENT/$dir ]; then
+                  echo "Creating $GHOST_CONTENT/$dir directory"
+                  mkdir -pv $GHOST_CONTENT/$dir && chown -Rfv 65532:65532 $GHOST_CONTENT/$dir || echo "Error creating $GHOST_CONTENT/$dir directory"
+                fi
+              done
 
+              echo "Changing ownership of $GHOST_CONTENT/themes directory"
+              chown -Rf 65532:65532 $GHOST_CONTENT/themes && echo "chown ok on thenmes" || echo "Error changing ownership of $GHOST_CONTENT/themes directory"
 
-            echo 'Delete and clean $GHOST_CONTENT/public directory and recreate it'
-            rm -rfv $GHOST_CONTENT/public && mkdir -pv $GHOST_CONTENT/public || echo 'Error deleting and cleaning $GHOST_CONTENT/public directory and recreating it' && true
+              echo "Changing ownership of $GHOST_CONTENT/public directory"
+              chown -Rf 65532:65532 $GHOST_CONTENT/public && chown ok in public|| echo "Error changing ownership of $GHOST_CONTENT public directory"
+              exit 0
 
-            echo 'Check if the directory $GHOST_CONTENT/themes ownership is different from UID 1000 and GID 1000, if so, change it to 1000:1000 recursively and verbose.'
-            if [ "$(stat -c '%u:%g' $GHOST_CONTENT/themes)" != "1000:1000" ]; then
-              echo 'Changing ownership of $GHOST_CONTENT/themes directory to 1000:1000'
-              chown -Rf 1000:1000 $GHOST_CONTENT/themes || echo 'Error changing ownership of $GHOST_CONTENT/themes directory to 1000:1000' && true
-            fi
-
-            echo 'Check if the directory $GHOST_CONTENT/public ownership is different from UID 1000 and GID 1000, if so, change it to 1000:1000 recursively and verbose.'
-            if [ "$(stat -c '%u:%g' $GHOST_CONTENT/public)" != "1000:1000" ]; then
-              echo 'Changing ownership of $GHOST_CONTENT/public directory to 1000:1000'
-              chown -Rf 1000:1000 $GHOST_CONTENT/public || echo 'Error changing ownership of $GHOST_CONTENT/public directory to 1000:1000' && true
-            fi
-
-        volumeMounts:
-        - name: ghost-content
-          mountPath: /var/lib/ghost/content
-          readOnly: false
+          volumeMounts:
+            - name: ghost-content
+              mountPath: /var/lib/ghost/content
+              readOnly: false
 
       containers:
-      - name: ghost
-        image: ghcr.io/sredevopsorg/ghost-on-kubernetes:main
-        imagePullPolicy: Always
-        ports:
         - name: ghost
-          containerPort: 2368
-          protocol: TCP
+          image: ghcr.io/sredevopsorg/ghost-on-kubernetes:main
+          imagePullPolicy: Always
+          ports:
+            - name: ghost
+              containerPort: 2368
+              protocol: TCP
 
-        # You should uncomment the following lines in production. Change the values according to your environment.
+          # You should uncomment the following lines in production. Change the values according to your environment.
 
-        # livenessProbe:
-        #   httpGet:
-        #     path: /ghost/api/v4/admin/site/
-        #     port: ghk8s
-        #     httpHeaders:
-        #     - name: X-Forwarded-Proto
-        #       value: https
-        #     - name: Host
-        #       value: tests.yourdomain.com
-        #   periodSeconds: 3600
-        #   timeoutSeconds: 3
-        #   successThreshold: 1
-        #   failureThreshold: 1
-        #   initialDelaySeconds: 60
+          readinessProbe:
+            httpGet:
+              path: /ghost/api/v4/admin/site/
+              port: ghk8s
+              httpHeaders:
+                - name: X-Forwarded-Proto
+                  value: https
+                - name: Host
+                  value: rookian.dev
+            periodSeconds: 10
+            timeoutSeconds: 3
+            successThreshold: 1
+            failureThreshold: 3
+            initialDelaySeconds: 10
 
-        env:
-        - name: NODE_ENV
-          value: production
-        - name: TZ
-          value: America/Santiago
-        resources:
-          limits:
-            cpu: 800m
-            memory: 800Mi
-          requests:
-            cpu: 100m
-            memory: 200Mi
+          livenessProbe:
+            httpGet:
+              path: /ghost/api/v4/admin/site/
+              port: ghk8s
+              httpHeaders:
+                - name: X-Forwarded-Proto
+                  value: https
+                - name: Host
+                  value: rookian.dev
+            periodSeconds: 3600
+            timeoutSeconds: 3
+            successThreshold: 1
+            failureThreshold: 1
+            initialDelaySeconds: 60
 
-        volumeMounts:
-        - name: ghost-content
-          mountPath: /var/lib/ghost/content
-          readOnly: false
-        - name: ghost-config-prod
-          readOnly: true
-          mountPath: /var/lib/ghost/config.production.json
-          subPath: config.production.json
-        - name: tmp # This is the temporary volume mount to allow loading themes
-          mountPath: /tmp
-          readOnly: false
-        securityContext:
-          readOnlyRootFilesystem: true
-          allowPrivilegeEscalation: false
-          runAsNonRoot: true
-          runAsUser: 1000
+          env:
+            - name: NODE_ENV
+              value: production
+          resources:
+            limits:
+              cpu: 800m
+              memory: 800Mi
+            requests:
+              cpu: 100m
+              memory: 200Mi
+
+          volumeMounts:
+            - name: ghost-content
+              mountPath: /home/nonroot/app/ghost/content
+              readOnly: false
+            - name: ghost-config-prod
+              readOnly: true
+              mountPath: /home/nonroot/app/ghost/config.production.json
+              subPath: config.production.json
+            - name: tmp # This is the temporary volume mount to allow loading themes
+              mountPath: /tmp
+              readOnly: false
+          securityContext:
+            readOnlyRootFilesystem: true
+            allowPrivilegeEscalation: false
+            runAsNonRoot: true
+            runAsUser: 65532
 
       restartPolicy: Always
       terminationGracePeriodSeconds: 15
@@ -162,7 +167,6 @@ spec:
       #               operator: In
       #               values:
       #                 - "true"
-
 
       securityContext: {}
       schedulerName: default-scheduler
diff --git a/apps/ghost/mysql.yaml b/apps/ghost/mysql.yaml
--- a/apps/ghost/mysql.yaml
+++ b/apps/ghost/mysql.yaml
@@ -20,92 +20,89 @@ spec:
     metadata:
       labels:
         app: mysql-ghost
-      # annotations:
-      #   container.apparmor.security.beta.kubernetes.io/mysql-ghost: runtime/default
     spec:
       initContainers:
-      - name: mysql-ghost-init
-        securityContext:
-          allowPrivilegeEscalation: false
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: docker.io/busybox:stable-musl
-        imagePullPolicy: IfNotPresent
-        command:
-        - /bin/sh
-        - -c
-        - |
-          set -e
-          echo 'Changing ownership of mysql mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 999:999' && true
-          echo 'Changing ownership of tmp mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 999:999' && true
-          echo 'Changing ownership of socket mount directory to 999:999'
-          chown -Rfv 999:999 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 999:999' && true
-          exit 0
-          
-          
-        volumeMounts:
-        - name: mysql-ghost-volume
-          mountPath: /mnt/mysql
-          subPath: mysql-empty-subdir
-          readOnly: false
+        - name: mysql-ghost-init
+          securityContext:
+            allowPrivilegeEscalation: false
+            privileged: false
+            readOnlyRootFilesystem: true
+          image: docker.io/busybox:stable-musl
+          imagePullPolicy: IfNotPresent
+          command:
+            - /bin/sh
+            - -c
+            - |
+              set -e
+              echo 'Changing ownership of mysql mount directory to 65534:65534'
+              chown -Rfv 65534:65534 /mnt/mysql || echo 'Error changing ownership of mysql mount directory to 65534:65534' && true
+              echo 'Changing ownership of tmp mount directory to 65534:65534'
+              chown -Rfv 65534:65534 /mnt/tmp || echo 'Error changing ownership of tmp mount directory to 65534:65534' && true
+              echo 'Changing ownership of socket mount directory to 65534:65534'
+              chown -Rfv 65534:65534 /mnt/var/run/mysqld || echo 'Error changing ownership of socket mount directory to 65534:65534' && true
+              exit 0
 
-        - name: mysql-ghost-tmp
-          mountPath: /mnt/tmp
-          readOnly: false
+          volumeMounts:
+            - name: mysql-ghost-volume
+              mountPath: /mnt/mysql
+              subPath: mysql-empty-subdir
+              readOnly: false
 
-        - name: mysql-ghost-socket
-          mountPath: /mnt/var/run/mysqld
-          readOnly: false
-        
-        # YOu can ajust the resources according to your needs
-        resources:
-          requests:
-            memory: 0Mi
-            cpu: 0m
-          limits:
-            memory: 1Gi
-            cpu: 900m
+            - name: mysql-ghost-tmp
+              mountPath: /mnt/tmp
+              readOnly: false
+
+            - name: mysql-ghost-socket
+              mountPath: /mnt/var/run/mysqld
+              readOnly: false
+
+          # YOu can ajust the resources according to your needs
+          resources:
+            requests:
+              memory: 0Mi
+              cpu: 0m
+            limits:
+              memory: 1Gi
+              cpu: 900m
 
       containers:
-      - name: mysql-ghost
-        securityContext:
-          allowPrivilegeEscalation: false
-          privileged: false
-          readOnlyRootFilesystem: true
-          runAsNonRoot: true
-          runAsUser: 999
+        - name: mysql-ghost
+          securityContext:
+            allowPrivilegeEscalation: false
+            privileged: false
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+            runAsUser: 65534
 
-        image: docker.io/mysql:8.2
-        imagePullPolicy: IfNotPresent # You can change this value according to your needs
-        envFrom:
-        - secretRef:
-            name: mysql-ghost-config
-        resources:
-          requests:
-            memory: 500Mi # You can change this value according to your needs
-            cpu: 400m # You can change this value according to your needs
-          limits:
-            memory: 1Gi # You can change this value according to your needs
-            cpu: 900m # You can change this value according to your needs
-        ports:
-        - containerPort: 3306
-          protocol: TCP
-          name: mysql-ghost
-        volumeMounts:
-        - name: mysql-ghost-volume
-          mountPath: /var/lib/mysql
-          subPath: mysql-empty-subdir
-          readOnly: false
+          image: docker.io/mysql:8.4
+          imagePullPolicy: IfNotPresent # You can change this value according to your needs
+          envFrom:
+            - secretRef:
+                name: mysql-ghost-config
+          resources:
+            requests:
+              memory: 500Mi # You can change this value according to your needs
+              cpu: 400m # You can change this value according to your needs
+            limits:
+              memory: 1Gi # You can change this value according to your needs
+              cpu: 900m # You can change this value according to your needs
+          ports:
+            - containerPort: 3306
+              protocol: TCP
+              name: mysql-ghost
+          volumeMounts:
+            - name: mysql-ghost-volume
+              mountPath: /var/lib/mysql
+              subPath: mysql-empty-subdir
+              readOnly: false
 
-        - name: mysql-ghost-tmp
-          mountPath: /tmp
-          readOnly: false
+            - name: mysql-ghost-tmp
+              mountPath: /tmp
+              readOnly: false
 
-        - name: mysql-ghost-socket
-          mountPath: /var/run/mysqld
-          readOnly: false
+            - name: mysql-ghost-socket
+              mountPath: /var/run/mysqld
+              readOnly: false
 
       automountServiceAccountToken: false
 
@@ -120,17 +117,17 @@ spec:
       #               values:
       #                 - "true"
 
-      # securityContext:
-      #   seccompProfile:
-      #     type: RuntimeDefault
+      securityContext:
+        seccompProfile:
+          type: RuntimeDefault
 
       volumes:
-      - name: mysql-ghost-volume
-        persistentVolumeClaim:
-          claimName: ghost-database-pvc
-      - name: mysql-ghost-tmp
-        emptyDir:
-          sizeLimit: 128Mi
-      - name: mysql-ghost-socket
-        emptyDir:
-          sizeLimit: 128Mi
+        - name: mysql-ghost-volume
+          persistentVolumeClaim:
+            claimName: ghost-database-pvc
+        - name: mysql-ghost-tmp
+          emptyDir:
+            sizeLimit: 128Mi
+        - name: mysql-ghost-socket
+          emptyDir:
+            sizeLimit: 128Mi
